<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class StudentsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('students')->delete();
        
        \DB::table('students')->insert(array (
            0 => 
            array (
                'id' => 1,
                'user_id' => 7,
                'course_id' => 1,
                'IDNumber' => 'IMC/BAC/101',
                'firstname' => 'Alphaxad',
                'middlename' => 'John',
                'lastname' => 'Kakulu',
                'phone' => '+255-743-196-599',
                'email' => 'alpha@gmail.com',
                'year' => '2',
                'level' => 'Degree',
                'faculty_id' => 1,
                'status' => 'active',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'user_id' => 8,
                'course_id' => 1,
                'IDNumber' => 'IMC/BAC/102',
                'firstname' => 'Jamar',
                'middlename' => 'John',
                'lastname' => 'Jamar',
                'phone' => '+255-743-196-599',
                'email' => 'jamar@gmail.com',
                'year' => '1',
                'level' => 'Degree',
                'faculty_id' => 1,
                'status' => 'active',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'user_id' => 9,
                'course_id' => 1,
                'IDNumber' => 'IMC/BAC/103',
                'firstname' => 'Goodluck',
                'middlename' => 'kessy',
                'lastname' => 'Goodluck',
                'phone' => '+255-743-196-599',
                'email' => 'goodluck@gmail.com',
                'year' => '2',
                'level' => 'Degree',
                'faculty_id' => 1,
                'status' => 'active',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'user_id' => 10,
                'course_id' => 2,
                'IDNumber' => 'IMC/BBF/104',
                'firstname' => 'Ommary',
                'middlename' => 'Crinton',
                'lastname' => 'Ommary',
                'phone' => '+255-743-196-599',
                'email' => 'ommary@gmail.com',
                'year' => '1',
                'level' => 'Degree',
                'faculty_id' => 1,
                'status' => 'active',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'user_id' => 11,
                'course_id' => 2,
                'IDNumber' => 'IMC/BBF/105',
                'firstname' => 'Abdully',
                'middlename' => 'kessy',
                'lastname' => 'Kawambwa',
                'phone' => '+255-743-196-599',
                'email' => 'abdully@gmail.com',
                'year' => '2',
                'level' => 'Degree',
                'faculty_id' => 1,
                'status' => 'active',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'user_id' => 12,
                'course_id' => 3,
                'IDNumber' => 'IMC/BBF/106',
                'firstname' => 'Kakulu',
                'middlename' => 'kessy',
                'lastname' => 'Jeremiah',
                'phone' => '+255-743-196-599',
                'email' => 'kakulu@gmail.com',
                'year' => '2',
                'level' => 'Degree',
                'faculty_id' => 1,
                'status' => 'active',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'user_id' => 13,
                'course_id' => 4,
                'IDNumber' => 'IMC/BAIT/107',
                'firstname' => 'Jannet',
                'middlename' => 'Gomez',
                'lastname' => 'Alphonce',
                'phone' => '+255-743-196-599',
                'email' => 'jannnet@gmail.com',
                'year' => '2',
                'level' => 'Degree',
                'faculty_id' => 1,
                'status' => 'active',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'user_id' => 14,
                'course_id' => 4,
                'IDNumber' => 'IMC/BAIT/108',
                'firstname' => 'Aisha',
                'middlename' => 'Pimbili',
                'lastname' => 'Panuel',
                'phone' => '+255-743-196-599',
                'email' => 'aish@gmail.com',
                'year' => '2',
                'level' => 'Degree',
                'faculty_id' => 1,
                'status' => 'active',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'user_id' => 15,
                'course_id' => 4,
                'IDNumber' => 'IMC/BAIT/109',
                'firstname' => 'Juma',
                'middlename' => 'kessy',
                'lastname' => 'Jeremiah',
                'phone' => '+255-743-196-599',
                'email' => 'juma@gmail.com',
                'year' => '2',
                'level' => 'Degree',
                'faculty_id' => 1,
                'status' => 'active',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'user_id' => 16,
                'course_id' => 5,
                'IDNumber' => 'IMC/ODAC/1010',
                'firstname' => 'Tinnah',
                'middlename' => 'Joseph',
                'lastname' => 'Alex',
                'phone' => '+255-743-196-599',
                'email' => 'Tinnah@gmail.com',
                'year' => '1',
                'level' => 'Diploma',
                'faculty_id' => 1,
                'status' => 'active',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'user_id' => 17,
                'course_id' => 5,
                'IDNumber' => 'IMC/ODAC/1011',
                'firstname' => 'Manase',
                'middlename' => 'Pembeko',
                'lastname' => 'Kimani',
                'phone' => '+255-743-196-599',
                'email' => 'Pembeko@gmail.com',
                'year' => '1',
                'level' => 'Diploma',
                'faculty_id' => 1,
                'status' => 'active',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'user_id' => 18,
                'course_id' => 5,
                'IDNumber' => 'IMC/ODAC/1012',
                'firstname' => 'Rodger',
                'middlename' => 'kessy',
                'lastname' => 'mafulu',
                'phone' => '+255-743-196-599',
                'email' => 'Rodger@gmail.com',
                'year' => '1',
                'level' => 'Diploma',
                'faculty_id' => 1,
                'status' => 'active',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'user_id' => 19,
                'course_id' => 5,
                'IDNumber' => 'IMC/ODBF/1013',
                'firstname' => 'Salumu',
                'middlename' => 'kessy',
                'lastname' => 'Salumu',
                'phone' => '+255-743-196-599',
                'email' => 'salumu@gmail.com',
                'year' => '1',
                'level' => 'Diploma',
                'faculty_id' => 1,
                'status' => 'active',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'user_id' => 20,
                'course_id' => 5,
                'IDNumber' => 'IMC/ODBF/1014',
                'firstname' => 'Martha',
                'middlename' => 'Benson',
                'lastname' => 'january',
                'phone' => '+255-743-196-599',
                'email' => 'benson@gmail.com',
                'year' => '1',
                'level' => 'Diploma',
                'faculty_id' => 1,
                'status' => 'active',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'user_id' => 21,
                'course_id' => 5,
                'IDNumber' => 'IMC/ODBF/1015',
                'firstname' => 'Maila',
                'middlename' => 'Juma',
                'lastname' => 'ramadhani',
                'phone' => '+255-743-196-599',
                'email' => 'maila@gmail.com',
                'year' => '1',
                'level' => 'Diploma',
                'faculty_id' => 1,
                'status' => 'active',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            15 => 
            array (
                'id' => 16,
                'user_id' => 28,
                'course_id' => 6,
                'IDNumber' => 'IMC/BIT/201',
                'firstname' => 'Alphaxad',
                'middlename' => 'John',
                'lastname' => 'Kakulu',
                'phone' => '+255-743-196-599',
                'email' => 'alpha@gmail.com',
                'year' => '2',
                'level' => 'Degree',
                'faculty_id' => 2,
                'status' => 'active',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            16 => 
            array (
                'id' => 17,
                'user_id' => 29,
                'course_id' => 6,
                'IDNumber' => 'IMC/BIT/202',
                'firstname' => 'Jamar',
                'middlename' => 'John',
                'lastname' => 'Jamar',
                'phone' => '+255-743-196-599',
                'email' => 'jamar@gmail.com',
                'year' => '1',
                'level' => 'Degree',
                'faculty_id' => 2,
                'status' => 'active',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'user_id' => 30,
                'course_id' => 6,
                'IDNumber' => 'IMC/BIT/203',
                'firstname' => 'Goodluck',
                'middlename' => 'kessy',
                'lastname' => 'Goodluck',
                'phone' => '+255-743-196-599',
                'email' => 'goodluck@gmail.com',
                'year' => '2',
                'level' => 'Degree',
                'faculty_id' => 2,
                'status' => 'active',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            18 => 
            array (
                'id' => 19,
                'user_id' => 31,
                'course_id' => 6,
                'IDNumber' => 'IMC/BIT/204',
                'firstname' => 'Ommary',
                'middlename' => 'Crinton',
                'lastname' => 'Ommary',
                'phone' => '+255-743-196-599',
                'email' => 'ommary@gmail.com',
                'year' => '1',
                'level' => 'Degree',
                'faculty_id' => 2,
                'status' => 'active',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            19 => 
            array (
                'id' => 20,
                'user_id' => 32,
                'course_id' => 6,
                'IDNumber' => 'IMC/BIT/205',
                'firstname' => 'Abdully',
                'middlename' => 'kessy',
                'lastname' => 'Kawambwa',
                'phone' => '+255-743-196-599',
                'email' => 'abdully@gmail.com',
                'year' => '2',
                'level' => 'Degree',
                'faculty_id' => 2,
                'status' => 'active',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            20 => 
            array (
                'id' => 21,
                'user_id' => 33,
                'course_id' => 7,
                'IDNumber' => 'IMC/BCS/206',
                'firstname' => 'Salumu',
                'middlename' => 'kessy',
                'lastname' => 'Salumu',
                'phone' => '+255-743-196-599',
                'email' => 'salumu@gmail.com',
                'year' => '1',
                'level' => 'Degree',
                'faculty_id' => 2,
                'status' => 'active',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            21 => 
            array (
                'id' => 22,
                'user_id' => 34,
                'course_id' => 7,
                'IDNumber' => 'IMC/BCS/207',
                'firstname' => 'Martha',
                'middlename' => 'Benson',
                'lastname' => 'january',
                'phone' => '+255-743-196-599',
                'email' => 'benson@gmail.com',
                'year' => '2',
                'level' => 'Degree',
                'faculty_id' => 2,
                'status' => 'active',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            22 => 
            array (
                'id' => 23,
                'user_id' => 35,
                'course_id' => 7,
                'IDNumber' => 'IMC/BCS/208',
                'firstname' => 'Maila',
                'middlename' => 'Juma',
                'lastname' => 'ramadhani',
                'phone' => '+255-743-196-599',
                'email' => 'maila@gmail.com',
                'year' => '1',
                'level' => 'Degree',
                'faculty_id' => 2,
                'status' => 'active',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            23 => 
            array (
                'id' => 24,
                'user_id' => 36,
                'course_id' => 7,
                'IDNumber' => 'IMC/BCS/209',
                'firstname' => 'Ommary',
                'middlename' => 'Crinton',
                'lastname' => 'Ommary',
                'phone' => '+255-743-196-599',
                'email' => 'ommary@gmail.com',
                'year' => '1',
                'level' => 'Degree',
                'faculty_id' => 2,
                'status' => 'active',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            24 => 
            array (
                'id' => 25,
                'user_id' => 37,
                'course_id' => 7,
                'IDNumber' => 'IMC/BCS/210',
                'firstname' => 'Abdully',
                'middlename' => 'kessy',
                'lastname' => 'Kawambwa',
                'phone' => '+255-743-196-599',
                'email' => 'abdully@gmail.com',
                'year' => '2',
                'level' => 'Degree',
                'faculty_id' => 2,
                'status' => 'active',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            25 => 
            array (
                'id' => 26,
                'user_id' => 38,
                'course_id' => 8,
                'IDNumber' => 'IMC/ODIT/211',
                'firstname' => 'Tinnah',
                'middlename' => 'Joseph',
                'lastname' => 'Alex',
                'phone' => '+255-743-196-599',
                'email' => 'Tinnah@gmail.com',
                'year' => '1',
                'level' => 'Diploma',
                'faculty_id' => 2,
                'status' => 'active',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            26 => 
            array (
                'id' => 27,
                'user_id' => 39,
                'course_id' => 8,
                'IDNumber' => 'IMC/ODIT/212',
                'firstname' => 'Manase',
                'middlename' => 'Pembeko',
                'lastname' => 'Kimani',
                'phone' => '+255-743-196-599',
                'email' => 'Pembeko@gmail.com',
                'year' => '1',
                'level' => 'Diploma',
                'faculty_id' => 2,
                'status' => 'active',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            27 => 
            array (
                'id' => 28,
                'user_id' => 40,
                'course_id' => 8,
                'IDNumber' => 'IMC/ODIT/213',
                'firstname' => 'Rodger',
                'middlename' => 'kessy',
                'lastname' => 'mafulu',
                'phone' => '+255-743-196-599',
                'email' => 'Rodger@gmail.com',
                'year' => '1',
                'level' => 'Diploma',
                'faculty_id' => 2,
                'status' => 'active',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            28 => 
            array (
                'id' => 29,
                'user_id' => 41,
                'course_id' => 9,
                'IDNumber' => 'MC/ODCS/214',
                'firstname' => 'Salumu',
                'middlename' => 'kessy',
                'lastname' => 'Salumu',
                'phone' => '+255-743-196-599',
                'email' => 'salumu@gmail.com',
                'year' => '1',
                'level' => 'Diploma',
                'faculty_id' => 2,
                'status' => 'active',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            29 => 
            array (
                'id' => 30,
                'user_id' => 42,
                'course_id' => 9,
                'IDNumber' => 'IMC/ODCS/215',
                'firstname' => 'Martha',
                'middlename' => 'Benson',
                'lastname' => 'january',
                'phone' => '+255-743-196-599',
                'email' => 'benson@gmail.com',
                'year' => '1',
                'level' => 'Diploma',
                'faculty_id' => 2,
                'status' => 'active',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            30 => 
            array (
                'id' => 31,
                'user_id' => 43,
                'course_id' => 9,
                'IDNumber' => 'IMC/ODCS/216',
                'firstname' => 'Maila',
                'middlename' => 'Juma',
                'lastname' => 'ramadhani',
                'phone' => '+255-743-196-599',
                'email' => 'maila@gmail.com',
                'year' => '1',
                'level' => 'Diploma',
                'faculty_id' => 2,
                'status' => 'active',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
        ));
        
        
    }
}